[project]
name = "color-gomoku-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=0.28.0",
    "matplotlib>=3.5.0",
    "numpy>=1.21.0",
    "pygame>=2.5.0",
    "torch>=2.0.0",
    "wandb>=0.25.0",
]
